---
- name: ensure that java is installed
  become: yes
  yum:
    name: java-1.8.0-openjdk-devel
    state: latest

- name: java environment variables
  become: yes
  copy:
    src: java.sh
    dest: /etc/profile.d/java.sh
    group: root
    owner: root
    mode: 0644
