---
- include: epel.yml

- include: java.yml

- include: scala.yml

- include: apache-download.yml
  vars:
    url_path: "{{ zookeeper_url_path }}"
    file_name: "{{ zookeeper_tgz_file }}"

- include: apache-download.yml
  vars:
    url_path: "{{ kafka_url_path }}"
    file_name: "{{ kafka_tgz_file }}"
